### PR TITLE
New hide axis

### PR DESCRIPTION
**Pull request by rishiloyola**
Here is the pull request of my new changes to hide axis. I closed that branch.Please have a look at it.
Link to gh-pages - http://rishiloyola.github.io/lab-grapher/examples/index.html#earth-surface-temperature

### CODE REVIEW

**Comment by ddamelin** [comment]
This looks good to me. I want one other person to take a look though before we merge.

**Comment by sfentress** [comment]
When I go to the link at http://rishiloyola.github.io/lab-grapher/examples/index.html#earth-surface-temperature, I still see the axis values when I click the checkbox. Only the font size changes. Do you not see this?

**Comment by ddamelin** [comment]
They axis values on Rishi's site are gone for me. Checked a few browsers.

**Comment by scytacki** [comment]
The tick mark labels are gone for me too. Sam perhaps you are clicking the wrong checkbox? The responsive design checkbox makes the font size change as you describe.

**Comment by sfentress** [comment]
My mistake, I was tricked by the check boxes being to the right of the text fields.

I've just glanced through the code, it seems ok but I'll look at it a little deeper. Also, we'll need the built version to be committed as part of this PR, but if Rishi isn't able to build it then we could probably just build it ourselves.

**Comment by rishiloyola** [comment]
Here is my built version. So, is it fine now?

**Comment by sfentress** [comment]
Ok, it looks good to me. I made some small changes to simplify the logic. The changes have now been pulled in.

Thank you for sticking with this, Rishi!

**Comment by sfentress** [comment]
Hmmm... I don't know if we merged this branch in too soon... 

@ddamelin this is what I see when I use the new property in Lab: https://dl.dropbox.com/s/b8xk7b4ilt4g3j5/Screenshot%202015-04-07%2015.36.41.png

The y-axis label is always inside the graph.

**Comment by rishiloyola** [comment]
Hi @sfentress 
when I used this property for pendulum then it is working fine for me.
Link to screen shot- https://www.flickr.com/photos/130718981@N06/16981255991/player/
It may work if you change its spacing or width of graph.

**Comment by ddamelin** [comment]
@rishiloyola Can you verify that you see the same thing on the same interactive as Sam? If so, you should try to see if spacing makes a difference. We should not need to use a particular spacing with this mode, so there may be more work to do. First I want to see if you see the same results as Sam on the same interactive.

**Comment by rishiloyola** [comment]
@ddamelin  If you test it with the full screen then it is working fine for me.
link - https://www.flickr.com/photos/130718981@N06/17124971731/player/
but for the normal screen the y-axis label is always inside the graph.

**Comment by ddamelin** [comment]
Perhaps you can play with the layout some to see if you can characterize when this problem occurs. You might try setting explicit widths of the section containing the graph, or different paddings between the model and the graph. In the end we should not have to do a special layout, but understanding when the problem occurs might help track down how to fix it.

**Comment by rishiloyola** [comment]
okay, let me try this out.

**Pull request merged**
